name = "explorer-mcp"
type = "function"

[entrypoint]
prod = ".venv/bin/python3 src/server.py"
dev = "npx nodemon --exec uv run python src/server.py"

[env]
BROWSERBASE_API_KEY = "${secrets.BROWSERBASE_API_KEY}"
